{
  "cveTags": [],
  "descriptions": [
    {
      "lang": "en",
      "value": "Rejected reason: Duplicate of CVE-2024-5629."
    }
  ],
  "id": "CVE-2024-21506",
  "lastModified": "2024-06-05T15:15:11.173",
  "metrics": {},
  "published": "2024-04-06T05:15:07.210",
  "references": [],
  "sourceIdentifier": "report@snyk.io",
  "vulnStatus": "Rejected"
}