{
  "cveTags": [],
  "descriptions": [
    {
      "lang": "en",
      "value": "Rejected reason: DO NOT USE THIS CANDIDATE NUMBER. ConsultIDs: none. Reason: This candidate was withdrawn by its requestor. Notes: none"
    }
  ],
  "id": "CVE-2020-16149",
  "lastModified": "2023-11-07T03:18:12.687",
  "metrics": {},
  "published": "2020-09-03T15:15:11.363",
  "references": [],
  "sourceIdentifier": "cve@mitre.org",
  "vulnStatus": "Rejected"
}