{
  "cveTags": [],
  "descriptions": [
    {
      "lang": "en",
      "value": "Rejected reason: To maintain compliance with CNA rules, we have rejected this CVE record because it has not been used."
    }
  ],
  "id": "CVE-2022-43828",
  "lastModified": "2023-11-15T07:15:14.160",
  "metrics": {},
  "published": "2023-01-01T01:15:12.477",
  "references": [],
  "sourceIdentifier": "security@atlassian.com",
  "vulnStatus": "Rejected"
}